### ISSUE TITLE
Central dashboard 1.6 : Bug Manage Contributors

### ISSUE THREAD

**Issue by wg102** [StatCan/kubeflow#115] opened 2022-10-19 12:39 UTC
There is no working Manage Contributors https://kubeflow.aaw-dev.cloud.statcan.ca/manage-users :
` Error: servicerolebindings.rbac.istio.io "user-meow-external-com-clusterrole-edit" not found`

**What steps did you take and what happened:**
Try to add or delete a new contributor

**What did you expect to happen:**
It to add a contributor successfully

**Comment by mathis-marcotte** [comment] 2022-10-20 13:42
@wg102 I can't seem to replicate this issue. Can you confirm that it is still there and if so, where you tested it?

**Comment by Jose-Matsuda** [comment] 2022-10-20 13:46
I have encountered this issue here and there but only with seemingly specific cases.

**Comment by rohank07** [comment] 2022-10-20 13:48
I encountered this as well. I was not able to remove a contributor on my ns throwing the above err message. To resolve it, I deleted the rolebinding and then was able to add & delete the contributor.

**Comment by mathis-marcotte** [comment] 2022-10-20 13:52
I'm starting to think that this issue might be related to the lowercasing being done now on manage contributors. These rolebindings might have been created initially with caps in them, but now it expects lowercasing so it can't find the rolebindings because it's not an exact string match

**Comment by rohank07** [comment] 2022-10-20 14:14
It may be related. But the contributor emails in my ns did not have any caps in them. I also did a diff on v1.3 and v1.6 centraldashboard and there are no changes targeted towards rolebindings/servicerolebindings. 
![image](https://user-images.githubusercontent.com/28408586/196973208-cfc7155c-3568-4770-86fc-33945a40e082.png)

**Comment by mathis-marcotte** [comment] 2022-10-20 14:42
yeah this looks normal, all lower case, so yeah it doesn't look like it's related to what i was thinking
![image](https://user-images.githubusercontent.com/84033116/196980322-f9de6d36-0a76-4e02-af9e-6b426674bfcf.png)

**Comment by mathis-marcotte** [comment] 2022-10-20 15:31
I haven't been able to replicate it yet. But while testing with Jose's help, it seems like this affects just contributors that were already present before the 1.6 upgrade and not new ones. Is it possible that 1.6 handles contributors/rolebindings differently, or like creates them in a different way than before? Although either way they all appear normal when I `kubectl get rolebindings` for a given namespace

**Comment by bryanpaget** [comment] 2022-10-24 16:04
The Kubeflow 1.6 upgrade made some changes to the profile controller with update related to using the latest Istio API.

![image](https://user-images.githubusercontent.com/8212170/197572456-70643eff-a7b8-47c5-8405-68c164dda4cd.png)

https://github.com/mesosphere/kubeflow/commit/38c5b0853e0463d7807de753a3954e8c44c0d10c#diff-ff7d80e49068fc0d4fcabb7e93f91c0659a33cae13ddf0cf91a48341dcde8399L4

**Comment by mathis-marcotte** [comment] 2022-10-25 19:03
After some investigating done with the help of @Jose-Matsuda , we've determined what seems to be the cause of this issue. With the 1.6 update, it seems that when adding a new contributor to a given namespace, it creates both a `rolebinding` object AND a `servicerolebinding` object. This is different then before, where it would ONLY create a `rolebinding` object when adding a contributor. So now, when trying to delete a contributor of a namespace, it will try to delete both the `rolebinding` object, as well as the `servicerolebinding` object. But, in the cases of the pre-1.6 contributors that were initially added only as rolebindings, it can't find a related `servicerolebinding` object, so it returns an error saying it can't find that resource, even if it exists as just a `rolebinding` object. Also, it seems that for actually populating thoses lists of contributors to your namespaces, or when populating the list of namespaces you have access to, it only reads from the `rolebindings`, not the `servicerolebindings`.

**Comment by mathis-marcotte** [comment] 2022-10-25 19:09
Two other things that we noticed but don't seem to be related to this exact issue is that:
- [object Object] gets printed in the logs, like in the picture shown. 
- When creating role binding objects, numbers get removed while creating the binding name. So for example, there can't be both `wendy.gaultier@cloud.statcan.ca` and `wendy.gaultier2@cloud.statcan.ca` added as contributors to a given namespace since they are both going to result in the binding name `user-wendy-gaultier-cloud-statcan-ca-clusterrole`
- This one is more of a readability/clarity issue. In the logs when adding or deleting a contributor, if an error happens, it's always going to log it as "Unable to add a new contributor for {namespace}", regardless of if the action was actually to delete a contributor. But that is like that upstream too.

![image](https://user-images.githubusercontent.com/84033116/197860003-06ab0d9a-d80a-425c-8c11-7046e3217ea7.png)

**Comment by rohank07** [comment] 2022-10-25 19:44
Nice find! A solution can be write a patch to create ServiceRoleBindings for each rolebinding for roles with kubeflow-edit that currently exists in the namespace.

**Comment by rohank07** [comment] 2022-10-25 21:49
Seems like ServiceRole and ServiceRolebindings are deprecated with Istio 1.6+ https://github.com/kubeflow/kubeflow/issues/6018#issuecomment-868742500 The ServiceRolbinding is replaced with AuthorizationPolicy: https://v1-6-branch.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually

**Comment by mathis-marcotte** [comment] 2022-10-26 13:00
Yes that seems to be what Jose found out too when we were looking at things. 
It actually looks like upstream does use AuthorizationPolicy instead of ServiceRoleBindings https://github.com/kubeflow/kubeflow/blob/39bd199d65dc89ef8e2534d97247c5d71899309a/components/access-management/kfam/bindings.go#L96.
And we follow that exactly in our code. And this change from ServiceRoleBindings to AuthorizationPolicy came before the 1.6 upgrade. Looks like it came in our code in the 1.3 update. Is it possible that our dev instance is using an outdated image for the access-management component?

**Comment by wg102** [comment] 2022-10-28 19:45
@zachomedia @sylus 
This might apparently be very similar to something that happened between versions 1.2 and 1.3. Chuck mentioned you had worked on it and ran a script to fix the missing resources last time.

**Comment by Jose-Matsuda** [comment] 2022-10-31 11:50
This was the issue https://github.com/StatCan/daaas/issues/1048

**Comment by sylus** [comment] 2022-11-01 16:47
Can you create a Jira for this so I can track this down?

Will

**Comment by sylus** [comment] 2022-11-04 15:00
This should be all fixed now we were calling the old KFAM we had, I switched up back to upstream KFAM and not our override (was used for caching not fixed upstream)

https://github.com/StatCan/aaw-kubeflow-manifests/commit/14141d5f88f27f1889e312e48a7c352764de78a7

**Closed as completed by sylus** 2022-11-04 15:00 UTC
Labels: priority/soon
